stages:
  - build
  - linkcheck
  - deploy

# 1. Générez la doc pour toute branche
generate_doc:
  image: klakegg/hugo:0.107.0-ext-alpine-ci
  stage: build
  script:
    - hugo --environment production --minify
  artifacts:
    paths:
      - public

# 2. Vérification automatique des liens (lychee) après chaque build
lychee_check:
  image:
    name: lycheeverse/lychee:latest
    entrypoint: [""]
  stage: linkcheck
  dependencies:
    - generate_doc
  script:
    - mkdir -p lychee
    # Ajoutez ici vos exclusions pour ignorer certains liens si besoin (voir doc Lychee)
    - lychee --verbose --exclude-mail --no-progress --output lychee/lychee-report.txt public/
  artifacts:
    paths:
      - lychee/lychee-report.txt
    when: always
  #le job échouera si des liens morts sont détectés.

# 3. Déploiement manuel (uniquement sur master)
deploy_doc:
  image: adujardin/docker-lftp:latest
  stage: deploy
  script:
    - ls public/
    - echo "set ssl:verify-certificate no" > ~/.lftprc
    - lftp -e "mirror --exclude api/ --exclude api_2.X/ --exclude api_3.X/ --exclude cloud/ --exclude v3/ --only-newer -R -e -p -P=10 public/ /" -u $ZED_DOC_FTP_USER,$ZED_DOC_FTP_PASSWORD $ZED_DOC_FTP_HOST
  dependencies:
    - generate_doc
  only:
    - master
  when: manual
